### PR TITLE
Use config file in addition to command line args

### PR DESCRIPTION
**Pull request by yuewko**
John,

  Still need to tie up some loose ends. Just wanted you to see if this is what you have in mind.

   Thanks!

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Yes, but can we also leave the flags as options. So we:

Load the config file
Apply any flags on top of it

**Comment by yuewko** [comment]
Actually, I considered that too, but wasn't convinced that it will be used that way.

Anyway, I'll give that a shot.

**Comment by johnbelamaric** [comment]
In lab situations it's a lot easier to pass in params to a containerized app. For example, in Kubernetes you would need to create a ConfigMap to do the config file but can just pass in params otherwise.

**Comment by yuewko** [comment]
Got it!

OK, I was going to remove the option to remove cli option to pass in username/password. But, from what you said, I should leave it in for the use case you mentioned.

Make sense?

**Comment by johnbelamaric** [comment]
Yep

**Comment by yuewko** [comment]
John,

   Still a **WIP** - need doc updates.

This is how it works now:
- Code define hard defaults. This is used to instantiate _current_ defaults
- Parse command line ONLY to look for --conf-file
- If --conf-file specified, load it and overlay on top of _current_ defaults
- Set command line parser to use _current_ defaults, and parse command line to load all user specified parameters. User specified parameters overrides the _current_ defaults and become the effective options.

    Make sense?

**Comment by yuewko** [comment]
@johnbelamaric , I have updated README etc. It's ready to be merged if it looks ok to you.

**Comment by johnbelamaric** [comment]
I'll merge it now, but I think we should take a little time to add some tests.

**Pull request merged**
